version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/naay-core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/naay-py"
    schedule:
      interval: "weekly"
